<?php

/**
 * User: lidc
 * data:16-12-6
 */
class Controller_Cost extends Base
{

    protected $layout = 'layouts';
    protected $cost;
    protected $user;
    protected $log;
    protected $permi_id;
    protected $depart_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->cost = new Model_Cost();
        $this->user = new Model_User();
        $this->log = new Model_Log();
        $this->permi_id = $this->_session->get('PERMI_ID');
        $this->depart_id = DEPART_COST;
    }

    /**
     *  当月成本展示
     */
    public function indexAction()
    {
        $p = $this->_request->getQuery('p');
        $p = isset($p) ? $p : 1;

        $y = intval(date('Y', time()));
        $m = intval(date('m', time()));
        $newD = date('d', time());
        if ($m == 1) {
            $y -= 1;
            $m = 12;
        } else {
            $m -= 1;
        }

        $year = $this->_request->getQuery('year', $y);
        $month = $this->_request->getQuery('month', $m);
        $username = $this->_request->getQuery('username');
        $totalPayment = $this->_request->getQuery('total_payment');

        $start_time = strtotime($year . "-" . $month);//上个月初
        if ($month == 12) {
            $end_time = strtotime(($year + 1) . "-1");
        } else {
            $end_time = strtotime($year . "-" . ($month + 1));
        }

        $where['start_date'] = $start_time;
        $where['end_date'] = $end_time;

        if ($username) {
            $userId = $this->user->select('id', array('username[~]' => $username));
            if (!empty($userId)) {
                $where['user_id'] = $userId;
            } else {
                $where['user_id'] = -1;
            }
        }

        //累计收款
        if (isset($totalPayment) && $totalPayment) {
            //获取符合条件的累计id
            if ($newD < TIME_END_DAY && $newD > TIME_START_DAY) {
                $toList = $this->cost->getlist($where, '', '', true);
                $toList = $this->cost->total($toList['list'], $start_time);
                $listId = $this->getTotalId($toList, $totalPayment);
                $where['id'] = $listId;
            } else {
                $where['total_payment'] = $totalPayment;
            }
        }

        $list = $this->cost->getList($where, $p);
        $list['list'] = $this->cost->total($list['list'], $start_time);

        $page = new Component_Page($p, $list['count'], $this->_a, 20);

        //根据权限,显示标签和数据
        $userArry = $this->user->getUsername($this->depart_id);
        $NavAndData = $this->getNavAndcontent($list['list'], $userArry, $this->permi_id, $this->depart_id);

        //判断时间是否显示编辑过往数据功能
        $According = 1;//原为0
        if ($m == $month) $According = 1;
        $this->assign('According', $According);

        $navs = $NavAndData['navs'];
        $data = $NavAndData['data'];

        $this->assign('navs', $navs);
        $this->assign('fiveYears', $this->getYears());
        $this->assign('permissions', $this->getPermissions($this->permi_id));
        $this->assign('years', $year);
        $this->assign('month', $month);
        $this->assign('page', $page->display());
        $this->assign('permi_id', $this->permi_id);
        $this->assign('data', $data);
        $this->display('cost/index');
    }

    /**
     * 添加数据
     * */
    public function addCostAction()
    {
        if ($this->_request->getPost()) {
            $data = $this->_request->getPost();
            $contents = $data;
            if (isset($data['type']) && $data['type'] == 'update') {
                $id = $data['id'];
                $count = $this->cost->count(array('id' => $id));
                if ($count) {
                    $pic = $this->cost->get('m_pic', array('id' => $id));
                    $info['m_pic'] = $this->picAddrs($data['m_pic']);
                    if (isset($data['b_money']) && $data['b_money']) $info['b_money'] = $data['b_money'];
                    if (isset($data['m_consume']) && $data['m_consume']) $info['m_consume'] = $data['m_consume'];
                    if (isset($data['refund']) && $data['refund']) $info['refund'] = $data['refund'];
                    if (isset($data['b_money']) && $data['b_money']) $info['b_money'] = $data['b_money'];
                    if (isset($data['m_payment']) && $data['m_payment']) $info['m_payment'] = $data['m_payment'];
                    $info['update_time'] = time();
                    $re = $this->cost->update($info, array('id' => $id));
                    if ($re) $this->delPic($pic, $info['m_pic']);
                    $content = $this->contentItem($contents);
                    $this->log->add(2, $content);
                    ajaxReturn(1, '修改成功');
                }
                ajaxReturn(0, '修改失败');

            } else {
                $info['user_id'] = $data['user_id'];
                $info['m_consume'] = isset($data['m_consume']) ? $data['m_consume'] : '';
                $info['refund'] = isset($data['refund']) ? $data['refund'] : '';
                $info['b_money'] = isset($data['b_money']) ? $data['b_money'] : '';
                $info['m_payment'] = isset($data['m_payment']) ? $data['m_payment'] : '';
                $info['m_pic'] = $this->picAddrs($data['m_pic']);
                $info['create_time'] = time();
//                if($this->permi_id==PERMI_ADMIN){
                $year = isset($data['year']) ? $data['year'] : '';
                $month = isset($data['month']) ? $data['month'] : '';
                $info['date'] = strtotime(date($year . '-' . $month . '-01'));
//                }else{
//                    $info['date'] = strtotime(date('Y-m-01', strtotime('-1 month')));
//                }
                $res = $this->cost->get('id', array('AND' => array('user_id' => $info['user_id'], 'date' => $info['date'], 'del' => 0)));
                if ($res) {
                    ajaxReturn(2, '每个客户每月只可添加一条数据');
                }
                $re = $this->cost->insert($info);
                $content = $this->contentItem($contents);
                $this->log->add(1, $content);
            }
            if ($re) ajaxReturn(1, '添加成功');
            ajaxReturn(0, '添加失败');
        }
        echo '非法请求';
    }

    /**
     * 上传图片
     * 添加数据使用
     * */
    public function uploadAction()
    {
        if (!isset($_FILES['Filedata']['name'])) ajaxReturn(0, '上传错误');
        $data = json_decode(fn_upload_img('Filedata'));
        ajaxReturn(1, $data);
        exit;
    }


    /**
     * 客户名验证是否存在
     * */
    public function validationUserAction()
    {
        if ($this->_request->getPost()) {
            $username = $this->_request->getPost('username');
            if (!$username) ajaxReturn(0, '无此客户');
            $re = $this->user->get('id', array('AND' => array('username' => $username, 'depart_id' => $this->depart_id)));
            if ($re) ajaxReturn(1, $re);
            ajaxReturn(0, '无此客户');
        }
        ajaxReturn(0, '非法请求');
    }

    /**
     * 编辑/获取数据信息
     * */
    public function dataInfoAction()
    {
        if ($this->_request->getPost()) {
            $id = $this->_request->getPost('id');
            if (!$id) ajaxReturn(0, '');
            if ($this->permi_id < PERMI_SALES) {
                $re = $this->cost->get('*', array('id' => $id));
            } else {
                $re = $this->cost->get(array('id', 'user_id', 'm_consume', 'refund', 'm_pic'), array('id' => $id));
            }

            if (!$re) ajaxReturn(0, '获取数据失败');
            $username = $this->user->get('username', array('AND' => arraY('id' => $re['user_id'], 'depart_id' => $this->depart_id)));

            if ($re['m_pic']) $re['m_pic'] = $this->picAddrs($re['m_pic'], true);
            $re['username'] = $username ? $username : '';
            ajaxReturn(1, $re);
        }
    }

    /**
     * 删除
     * */
    public function delAction()
    {
        if ($this->_request->getPost()) {
            $id = $this->_request->getPost('id');
            if (!$id) ajaxReturn(0, '');
            $userinfo = $this->cost->get(array('id', 'user_id', 'b_money', 'm_consume', 'm_payment', 'total_payment', 'total_consume', 'refund', 'balance'), array('id' => $id));
            $user_name = $this->user->get('username', array('id' => $userinfo['user_id']));
            $re = $this->cost->update(array('del' => 1), array('id' => $id));
            if (!$re) ajaxReturn(0, '删除失败');
//            $m_pic = $this->cost->get('m_pic',array('id'=>$id));
//            $this->delPic($m_pic);
            $user_name = isset($user_name) ? $user_name : '未知用户';
            $data = $userinfo;
            $data['username'] = $user_name;
            $content = $this->contentItem($data);
            $this->log->add(3, $content);
            ajaxReturn(1, '删除成功');
        }
    }
}