<?php
/**
 * Income
 * User: lidc
 * data: 16-12-6
 */

class Controller_Income extends Base{

    protected $layout = 'layouts';
    protected $income;
    protected $user;
    protected $log='';
    protected $departAction = array(1=>'index',2=>'site',3=>'agent',4=>'gooleProject',5=>'dataCustom');
    protected $permi_id ;
    protected $depart_id;
    protected $login_url = 'http://login.juhuisuan.com/interface/';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->income = new Model_Income();
        $this->user = new Model_User();
        $this->log = new Model_Log();
        $this->permi_id = $this->_session->get('PERMI_ID');

    }

    /**
     * 销售部
     * */
    public function indexAction()
    {
        $p = $this->_request->getQuery('p');
        $p = isset($p) ? $p : 1;
        $years = $this->_request->getQuery('years',intval(date('Y', time())));
        $month = $this->_request->getQuery('month',intval(date('m', time())));
        $username = $this->_request->getQuery('username');
        $totalPayment = $this->_request->getQuery('total_payment');
        $this->depart_id = $this->_request->getQuery('depart_id',1);
        $where =array();
        $start_date = strtotime($years."-".$month);//月初
        if($month==12){//下个月初
            $end_date = strtotime(($years+1)."-1");
        }else{
            $end_date = strtotime($years."-".($month+1));
        }

        if($username){
            $userId = $this->user->get('id',array('username'=>$username));
            $where['user_id'] = $userId;
        }

        //累计收款
        if(!$totalPayment){
            $totalMoney = $this->income->totalPayment($totalPayment,$years,$end_date,$where);
        }else{
            $totalMoney = $this->income->totalPayment($totalPayment,$years,$end_date,$where);
            $userIdList= array();
            foreach($totalMoney as $k=>$v){
                $userIdList[] =$v['user_id'];
            }
            if($userIdList){
                $where['user_id'] = $userIdList;
            }else{
                $where['user_id'] =-1;
            }
        }

        $where['start_date'] = $start_date;
        $where['end_date'] = $end_date;

        //部门标签
        $NavAndData = $this->getNavAndData();

        if($this->permi_id>3){
            $this->depart_id  =array_keys ($NavAndData)[0];
        }

        $where['depart_id'] = $this->depart_id;
        $list = $this->income->getlist($where,$p);
        $page = new Component_Page($p, $list['count'], $this -> _a,20);

        //数据标签
        $userArry = $this->income->getUsername($this->depart_id);
        $NavAndcontent = $this->getNavAndcontent($list['list'],$userArry,$totalMoney);
        $this->assign('data',$NavAndcontent['data']);
        $this->assign('navs',$NavAndcontent['navs']);
        $this->assign('years',$this->income->getYears());
        $this->assign('month',$this->income->getMonth());
        $this->assign('Nav',$NavAndData);
        $this->assign('Apply',$this->depart_id);
        $this->assign('permi_id',$this->permi_id);
        $this->assign('page',$page -> display());
        $this->display('income/'.$this->departAction[$this->depart_id]);
    }

    /**
     *　根据权限,显示列表数据
     * @return array
     */
    private function getNavAndcontent($res,$userArry,$totalMoney) {
        $data = array();
        if($this->permi_id == 1 || $this->permi_id == 2 || $this->permi_id == 3) {
            if($this->depart_id==1){
                $navs = array('客户名','期初余额','本月消耗','本月收款','本月截图','累计收款','累计消耗','退款','余额','对账单');
            }elseif($this->depart_id==2){
                $navs = array('客户名','期初余额','本月充值','本月消耗','本月截图','累计充值','累计消耗','退款','余额','对账单');
            }else{
                $navs = array('客户名','期初余额','本月应收','本月收款','本月截图','累计应收','累计收款','退款','余额','对账单');
            }
            if(!empty($res)) {
                foreach($res as $k=>$v)
                {
                    $data[$k]['id'] = $v['id'];
                    if(count($userArry)) {
                        for ($i = 0; $i < count($userArry); $i++) {
                            if ($userArry[$i]['id'] == $v['user_id']) {
                                $data[$k]['username'] = $userArry[$i]['username'];
                            }
                        }
                    }
                    if(!isset($data[$k]['username'])){
                        $info['uid']=$v['user_id'];
                        $info['fields']='username';
                        $info['type']='getUserInfo';
                        $res = fn_get_contents($this->login_url. 'jhs', $info, 'post');
                        $eval_info = json_decode($res, true);
                        $data[$k]['username']=$eval_info['ret']==0?$eval_info['data']['username']:'未知用户';
                    }
                    $data[$k]['username'] = isset($data[$k]['username'])&&$data[$k]['username']?$data[$k]['username']:'未知用户';
                    $data[$k]['b_money'] = $v['b_money'];
                    $data[$k]['m_consume'] = $v['m_consume'];
                    $data[$k]['m_payment'] = $v['m_payment'];
                    $data[$k]['m_pic'] = $v['m_pic'];
                    if(isset($totalMoney[$v['user_id']])){
                        $data[$k]['total_payment'] = $totalMoney[$v['user_id']]['total_payment'];
                        $data[$k]['total_consume'] = $totalMoney[$v['user_id']]['total_consume'];
                    }
                    $data[$k]['status'] = $v['status']==1?'已收':'未收';
                    $data[$k]['refund'] = $v['refund'];
                    $data[$k]['balance'] = $v['balance'];
                }
            }
        } else {
            if($this->depart_id == 1){
                $navs = array('客户名','本月消耗','本月截图','退款');
            }else if($this->depart_id == 2){
                $navs = array('客户名','本月充值','本月截图','退款');
            }else{
                $navs = array('客户名','本月应收','本月截图','退款');
            }
            if(!empty($res)) {
                foreach($res as $k=>$v)
                {
                    $data[$k]['id'] = $v['id'];
                    if(count($userArry)){
                        for($i=0;$i<count($userArry);$i++){
                            if($userArry[$i]['id']==$v['user_id']){
                                $data[$k]['username'] = $userArry[$i]['username'];
                            }
                        }
                    }
                    $data[$k]['username'] = isset($data[$k]['username'])?$data[$k]['username']:'未知用户';
                    $data[$k]['m_consume'] = $v['m_consume'];
                    $data[$k]['m_pic'] = $v['m_pic'];
                    $data[$k]['refund'] = $v['refund'];
                }
            }
        }
        $NavAndData = array('navs'=>$navs,'data'=>$data);
        return $NavAndData;
    }

    /**
     *　根据权限,显示部门标签
     * @return array
     */
    private function getNavAndData()
    {
        $permi_id =$this->permi_id;
        if($permi_id){
            $navs =array();
            if($permi_id==1 || $permi_id==2 || $permi_id==3 ){
                $navs = array(1=>'销售部',2=>'站内',3=>'代理',4=>'谷歌项目',5=>'数据定制');
            }elseif($permi_id==4){
                $navs = array(1=>'销售部');
            }elseif($permi_id==5){
                $navs = array(2=>'站内');
            }elseif($permi_id==6){
                $navs = array(3=>'代理');
            }elseif($permi_id==7){
                $navs = array(4=>'谷歌项目');
            }elseif($permi_id==8){
                $navs = array(5=>'数据定制');
            } elseif($permi_id==9){
                $navs = array(5=>'渠道部');
            }
            return $navs;
        }
        return array();
    }

    /**
     * 余额添加
     * */
    public function addMoneyAction()
    {
        if($this->_request->getPOst()){
            $data =$this->_request->getPost();
            $count = $this->income->count(array('id'=>$data['id']));
            if($count){
                $info['b_money'] = $data['b_money'];
                $info['m_payment'] = $data['m_payment'];
                $re = $this->income->update($info,array('id'=>$data['id']));
            }
            if(isset($re) && $re){
                $content=$this->contentItem($data);
                $logs=$this->log->add(1,$content);
                if($logs['ret']==1)  ajaxReturn(1,'添加成功');
                ajaxReturn(0,'数据添加成功,日志添加失败');
            }else{
                ajaxReturn(0,'添加失败');
            }
        }
    }


    /**
     * 添加数据
     * */
    public function addIncomeAction()
    {
        if($this->_request->getPost()){
            $data = $this->_request->getPost();
            $contents=$data;
            if(isset($data['type']) && $data['type']=='update') {
                $id = $data['id'];
                $count = $this->income->count(array('id'=>$id));
                if($count){
                    $pic = $this->income->get('m_pic',array('id'=>$id));
                    $info['m_pic'] = $this->income->picAddrs($data['m_pic']);
                    $info['m_consume'] = $data['m_consume'];
                    $info['refund'] = $data['refund'];
                    $info['b_money'] = $data['b_money'];
                    $info['m_payment'] = $data['m_payment'];
                    $info['update_time'] =time();
                    $re = $this->income->update($info,array('id'=>$id));
                    if($re) $this->income->delPic($pic);
                    $content=$this->contentItem($contents);
                    $this->log->add(2,$content);
                }
                ajaxReturn(0,'修改失败');
            }else{
                $info['user_id'] =isset($data['user_id'])?$data['user_id']:'';
                $info['m_consume'] = isset($data['m_consume'])?$data['m_consume']:'';
                $info['refund'] = isset($data['refund'])?$data['refund']:'';
                $info['depart_id'] = isset($data['depart_id'])?$data['depart_id']:'';
                $info['b_money'] = isset($data['b_money'])?$data['b_money']:'';
                $info['m_payment'] = isset($data['m_payment'])?$data['m_payment']:'';
                $info['m_pic']=$this->income->picAddrs(isset($data['m_pic'])?$data['m_pic']:'');
                $info['create_time'] = time();
                $info['date'] = strtotime(date('Y-m-01', strtotime('-1 month')));
                $res = $this->income->get('id',array('AND'=>array('user_id'=>$info['user_id'],'date'=>$info['date'])));
                if($res)    ajaxReturn(2,'每个客户每月只可添加一条数据');
                $re = $this->income->insert($info);
                $content=$this->contentItem($contents);
                $this->log->add(1,$content);
            }
            if($re) ajaxReturn(1,'添加成功');
            ajaxReturn(0,'添加失败');
        }
        echo '非法请求';
    }

    /**
     * 上传图片
     * 添加数据使用
     * */
    public function uploadAction()
    {
        if(!isset($_FILES['Filedata']['name'])) ajaxReturn(0,'上传错误');
        $data = json_decode(fn_upload_img('Filedata'));
        ajaxReturn(1,$data);
        exit;
    }


    /**
     * 客户名验证是否存在
     * */
    public function validationUserAction()
    {
        if($this->_request->getPost()){
            $username =$this->_request->getPost('username');
            $depart_id =$this->_request->getPost('depart_id');
            if(!$username) ajaxReturn(0,'无此客户');
            $user= new Model_User();
            $re = $user->get('id',array('AND'=>array('username'=>$username,'depart_id'=>$depart_id)));
            if($re) ajaxReturn(1,$re);
            ajaxReturn(0,'无此客户');
        }
        ajaxReturn(0,'非法请求');
    }

    /**
     * 编辑/获取数据信息
     * */
    public function dataInfoAction()
    {
        if($this->_request->getPost()){
            $id = $this->_request->getPost('id');
            $depart_id = $this->_request->getPost('depart_id');
            if(!$id) ajaxReturn(0,'');
            $re = $this->income->get('*',array('id'=>$id));
            if(!$re) ajaxReturn(0,'获取数据失败');
            $username = $this->user->get('username',array('AND'=>arraY('id'=>$re['user_id'],'depart_id'=>$depart_id)));
            if($re['m_pic']) $re['m_pic'] = $this->income->picAddrs($re['m_pic'],true);
            $re['username'] =$username?$username:'';
            ajaxReturn(1,$re);
        }
    }

    /**
     * 删除
     * */
    public function delAction()
    {
        if($this->_request->getPost()){
            $id = $this->_request->getPost('id');
            if(!$id) ajaxReturn(0,'');
            $userid=$this->income->get('user_id',array('id'=>$id));
            $user_name=$this->user->get('username',array('id'=>$userid));
            $re = $this->income->delete(array('id'=>$id));
            if(!$re) ajaxReturn(0,'删除失败');
            $m_pic = $this->income->get('m_pic',array('id'=>$id));
            $this->income->delPic($m_pic);
            $user_name=isset($user_name)?$user_name:'未知用户';
            $data=getAuthName($_SESSION['PERMI_ID']).','.$user_name.',启冠网络股份有限公司,id='.$id;
            $content=$this->contentItem($data,1);
            $this->log->add(3,$content);
            ajaxReturn(1,'删除成功');
        }
    }


    /**
     * 修改对账状态
     * */
    public function updateStatusAction()
    {
        if($this->_request->getPost())
        {
            $id =$this->_request->getPost('id');
            $status =$this->_request->getPost('status');
            $statu = 0;
            if(!$id)  ajaxReturn(0,'参数错误');
            if($status==0) $statu=1;
            $re= $this->income->update(array('status'=>$statu),array('id'=>$id));

            if($re){
                $userid=$this->income->get('user_id',array('id'=>$id));
                $user_name=$this->user->get('username',array('id'=>$userid));
                $user_name=isset($user_name)?$user_name:'未知用户';
                $status=$status==1?'已对账':'未对账';
                $data=getAuthName($_SESSION['PERMI_ID']).',修改对账单状态为'.$status.',操作用户名:'.$user_name.',启冠网络股份有限公司,id='.$id;
                $content=$this->contentItem($data,1);
                $this->log->add(3,$content);
                ajaxReturn(1,'修改成功');
            }
            ajaxReturn(0,'修改失败');
        }

    }

}