<?php
/**
 * Created By:  PhpStorm
 * Author: zhanghuang@pv25.com
 * Date:  2016/12/6
 * Time:  11:43
 */
class Controller_User extends Base{

    protected $layout = 'layouts';
    protected $pay_url = 'http://login.juhuisuan.com/interface/';
    protected $user='';
    protected $log='';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->user = new  Model_User();
        $this->log= new Model_Log();
    }

    /**
     * @Author: zhanghuang@pv25.com
     * @Time:  2016-12-6
     * 用户管理首页
     */
    public function indexAction()
    {
        $page = $this -> _request -> getQuery('p');
        $page = $page ? $page : 1;
        $rows = $this -> _request -> getQuery('pageSize');
        if(!$rows) {
            $rows= 20;
        }
        $user_name = $this -> _request -> getQuery('user_name');
        $depart = $this -> _request -> getQuery('depart');
        $where=array();
        if($user_name){
            $where['user_name']=$user_name;
        }
        if($depart!=0){
            $where['depart']=$depart;
        }
        $list=$this->user->getList($where,$page,$rows);
        $page = new Component_Page($page, $list['count'], $this -> _a,$rows);
        $this -> assign('page', $page -> display());
        $this->assign('list',$list);
        $this->display('user/index');
    }


    /**
     * 添加/操作客户信息
     */
    public function addUserAction(){

        IF($this->_request->getPost()){
            $data = $this->_request->getPost();
            if(!$data) ajaxReturn(0,'数据错误');
            $user_info = $this->user->selectUserByName($data['username'],$data['depart_id']);
            if(!empty($user_info)){
                ajaxReturn(0,'此部门已存在该用户');
            }
            $info['username'] = $data['username'];
            $info['create_time'] = time();
            $info['depart_id'] =$data['depart_id'];
            $info['zhi_userid'] =$data['zhi_userid'];
            $re = $this->user->insert($info);
            if($re){
                $datas=array(
                    'username'=>$data['username'],
                    'depart_id'=>$data['depart_id']
                );
                $contents=$this->contentItem($datas,3);
                $this->log->add(1,$contents);
                ajaxReturn(1,$re);
            }
            ajaxReturn(0,'添加失败');
        }
        ajaxReturn(0,'非法请求');
    }

    /**
     *获取客户信息
     * */
    public function userInfoAction()
    {
        if($this->_request->getPost()){
            $id = $this->_request->getPost('id');
            if(!$id) ajaxReturn(0,'参数错误');
            $info = $this->user->get(array('id','username'),array('id'=>$id));
            if($info) ajaxReturn(1,$info);
            ajaxReturn(0,'获取失败');
        }
        ajaxReturn(0,'非法请求');
    }

    /**
     * @Author: zhanghuang@pv25.com
     * @Since:2016-12-09
     * @Info:验证用户名
     */
    public function validationUserAction()
    {
        if($this->_request->getPost()){
            $username =$this->_request->getPost('username');
            if(!$username) ajaxReturn(0,'用户必填');
            $re = $this->user->get('id',array('username'=>$username));

            $info['username'] = $username;
            $info['type'] = 'unique';
            $res = fn_get_contents($this->pay_url. 'jhs', $info, 'post');
            $eval_info = json_decode($res, true);
            if($re) ajaxReturn(0,$re);
            ajaxReturn(1,isset($eval_info['data']['id'])?$eval_info['data']['id']:0);
        }
        ajaxReturn(0,'非法请求');
    }

}