<?php
/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-2-8
 * Time: 上午10:30
 */
class Controller_Advert  extends Base{

    protected $layout = "layouts";
    protected $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new Model_Advert();
    }

    /**
     *待审核列表
     * */
    public function checkAction()
    {
        $p = fn_get_val('p', 1);
        $data = $this->_request->getQuery();
        $year = date("Y");
        $month = date("m");
        if(!isset($data['start_date'])||!isset($data['end_date'])||$data['start_date']==''||$data['end_date']==''){
            $data['start_date']=$year."-".$month."-1";
            $data['end_date']=date('Y-m-d',time());
        }
        $data['review_status'] = 0;
        $list = $this->model->getList($data,$p,10);
        $this->assign('count', $list['count']);
        $this->assign('list',$list['list']);
        $this->display('advert/check');
    }

    /**
     * 已审核列表
     * */
    public function listAction()
    {
        $p = fn_get_val('p', 1);
        $data = $this->_request->getQuery();
        $data['check_status'] = 1;
        $year = date("Y");
        $month = date("m");
        if(!isset($data['start_date'])||!isset($data['end_date'])||$data['start_date']==''||$data['end_date']==''){
            $data['start_date']=$year."-".$month."-1";
            $data['end_date']=date('Y-m-d',time());
        }
        $list = $this->model->getlist($data,$p,10);
        $this->assign('count', $list['count']);
        $this->assign('list',$list['list']);
        $this->display('advert/list');
    }

    /**
     * 权重修改
     * */
    public function weightAction()
    {
        $info = $this->_request->getQuery();
        if(!$info['id']){
            fn_ajax_return(1, "参数错误！", "");
        }
        $data['weight']= $info['weight'];
        $where['id'] = $info['id'];
        $this->model->editSimple($where,$data);
        fn_ajax_return(0, "编辑成功", '');
    }


    /**
     * 编辑信息
     * */
    public function editAction()
    {
        $info = $this->_request->getQuery();
        if(!$info['id']){
            fn_ajax_return(1, "参数错误！", "");
        }
        $data['pic']= $info['pic'];
        $data['click_url']= $info['click_url'];
        $re = $this->model->verification($data);
        if($re!=$info['id']){
            $data['review_status']= 0;
        }
        $data['begin_time']= strtotime($info['begin_time']);
        $data['end_time']= strtotime($info['end_time']);
        $data['day_limit']= $info['day_limit'];
        $data['title']= $info['title'];
        $data['house_name']= $info['house_name'];
        $where['id'] = $info['id'];
        $this->model->editSimple($where,$data);
        if($info['id']){
            $crowdPackRelation = new Model_AdvertPackRelation();
            $crowdPackRelation->delete(['ad_id'=>$info['id']]);
            if(isset($info['pack_id']) && $info['pack_id']){
                $packId = explode(',',$info['pack_id']);
                foreach ($packId as $value)
                {
                    $crowdPackRelation->insert(['ad_id'=>$info['id'],'pack_id'=>$value]);
                }
            }
        }
        fn_ajax_return(0, "编辑成功", '');
    }

    /**
     * 审核
     * */
    public function checkAdvertAction()
    {
        $info = $this->_request->getQuery();
        if(!$info['id']){
            fn_ajax_return(1, "参数错误！", "");
        }
        if ($info['review_status']!=1){
            $data['reason'] = trim($info['reason']);
        }
        if($info['review_status']==2 && isset($info['reason']) && !trim($info['reason'])){
            fn_ajax_return(1, "必须填有内容，才可以提交！", "");
        }
        $data['review_status']= $info['review_status'];
        $where['id'] = $info['id'];
        $re = $this->model->editSimple($where,$data);

        //审核状态  0 等待审核·[未审核] 1 审核通过 2未通过
        if($re && $data['review_status']==1){
            $info = $this->model->getInfo($info['id']);
            $pint = new Putin($info['id'],$info['user_id']);
            $pint->Open();
        }
        fn_ajax_return(0, "审核成功", '');
    }

    /**
     * 获取信息
     * */
    public function getInfoAction()
    {
        $id = $this->_request->getQuery('id');
        if(!$id){
            fn_ajax_return(1, "参数错误！", "");
        }
        $info =$this->model->getInfo($id);
        if($info['conditi'] && $info['conditi']!='null') {
            $json = json_decode($info['conditi'],true);
            if(isset($json['end_lat'])) unset($json['end_lat']);
            if(isset($json['end_lon'])) unset($json['end_lon']);
            if(isset($json['start_lat'])) unset($json['start_lat']);
            if(isset($json['start_lon'])) unset($json['start_lon']);
            $info['conditi'] = implode(',', $json);
        }elseif ($info['conditi']=='null'){
            $info['conditi']='';
        }
        $pack = new Model_CrowdPack();
        $advertPack = new Model_AdvertPackRelation();
        //获取所属人群包
        $info['Crowdpack'] = $pack->getCrowdPack(['uid'=>$info['user_id']],['id','name','conditions','tp']);
        //获取选中人群包
        $info['AdvertPack'] = $advertPack->getAdvertPack(['ad_id'=>$info['id']]);
        fn_ajax_return(0, "", $info);
        exit;
    }


}
