<?php
/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-2-8
 * Time: 上午10:11
 */
class Controller_System extends Base
{

    protected $layout = "layouts";
    private $errorMsg = array();
    protected $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new Model_Admin();
    }

    public function addAction()
    {
        if($this->_request->isPost()){
            $data = $this->_request->getPost();
            $result = $this->model->add($data);
            if (is_array($result) && count($result) > 0) {
                $this->errorMsg = $result;
            } else {
                fn_js_redirect('添加成功！', '');
            }
        }
        $this->assign('errorMsg', $this->errorMsg);
        $this->display('system/add');
    }


    /**
     * 账号列表
     * */
    public function listAction()
    {
        $p = fn_get_val('p', 1);
        $info = $this->_request->getQuery();
        $list = $this->model->getList($info,$p,10);
        $this->assign('count', $list['count']);
        $this->assign('list',$list['list']);
        $this->display('system/list');
    }

    /**
     * 编辑
     * */
    public function editAction()
    {
        if($this->_request->isPost())
        {
            $data = $this->_request->getPost();
            $result = $this->model->editInfo($data);
            if (is_array($result) && count($result) > 0) {
                $this->errorMsg = $result;
            } else {
                fn_js_redirect('修改成功！', '/Mars/system/list');
            }
        }

        $id = fn_get_val('id', -1);
        $this->assign('errorMsg', $this->errorMsg);
        $info = $this->model->get('*',array('id'=>$id));
        $this->assign('info',$info);
        $this->display('system/edit');

    }

    /**
     * 账号信息
     * */
    public function infoAction()
    {
        $this->getView()->setLayout("");
        $info = $this->_session->get("userinfo");
        $this->assign('info',$info);
        $this->display('system/info');
    }

    /**
     * 密码重置
     * */
    public function  resetPwdAction()
    {
        $this->getView()->setLayout("");
        $data = $this->_request->getPost();
        $info = $this->_session->get("userinfo");
        $result = $this->model->editPwd($data,$info);
        if (is_array($result)) {
            $this->errorMsg = $result;
        } else {
            fn_js_redirect('修改成功！', 'info');
        }
        $info = $this->_session->get("userinfo");
        $this->assign('info',$info);
        $this->assign('errorMsg', $this->errorMsg);
        $this->display('system/info');

    }

    /**
     * 账号删除
     * */
    public function delAction()
    {
        $id = $this->_request->getParam('id');
        $status = $this->model->get('status',array('id'=>$id));
        if($status==2){
            $this->model->del($id);
            fn_js_redirect('删除成功！', '/Mars/system/list');
        }else{
            fn_js_redirect('删除失败，请先禁用账号！', '/Mars/system/list');
        }

    }


    /**
     * 账号冻结
     * */
    public function statusAction()
    {
        $id = $this->_request->getParam('id');
        $data['id'] = $id;
        $data['status'] =2;
        $this->model->editInfo($data);
        fn_js_redirect('冻结成功！', '/Mars/system/list');
    }

}
